/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTestRouteImport } from './routes/auth/test'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as PrPrNumberRouteRouteImport } from './routes/pr.$prNumber/route'
import { Route as PrPrNumberIndexRouteImport } from './routes/pr.$prNumber/index'
import { Route as PrPrNumberDiffRouteImport } from './routes/pr.$prNumber/diff'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OwnerRepoPullPull_numberRouteRouteImport } from './routes/$owner.$repo.pull.$pull_number/route'
import { Route as OwnerRepoPullPull_numberIndexRouteImport } from './routes/$owner.$repo.pull.$pull_number/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTestRoute = AuthTestRouteImport.update({
  id: '/auth/test',
  path: '/auth/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrPrNumberRouteRoute = PrPrNumberRouteRouteImport.update({
  id: '/pr/$prNumber',
  path: '/pr/$prNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const PrPrNumberIndexRoute = PrPrNumberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrPrNumberRouteRoute,
} as any)
const PrPrNumberDiffRoute = PrPrNumberDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => PrPrNumberRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoPullPull_numberRouteRoute =
  OwnerRepoPullPull_numberRouteRouteImport.update({
    id: '/$owner/$repo/pull/$pull_number',
    path: '/$owner/$repo/pull/$pull_number',
    getParentRoute: () => rootRouteImport,
  } as any)
const OwnerRepoPullPull_numberIndexRoute =
  OwnerRepoPullPull_numberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OwnerRepoPullPull_numberRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/test': typeof TestRoute
  '/pr/$prNumber': typeof PrPrNumberRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/test': typeof AuthTestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pr/$prNumber/diff': typeof PrPrNumberDiffRoute
  '/pr/$prNumber/': typeof PrPrNumberIndexRoute
  '/$owner/$repo/pull/$pull_number': typeof OwnerRepoPullPull_numberRouteRouteWithChildren
  '/$owner/$repo/pull/$pull_number/': typeof OwnerRepoPullPull_numberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/test': typeof TestRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/test': typeof AuthTestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pr/$prNumber/diff': typeof PrPrNumberDiffRoute
  '/pr/$prNumber': typeof PrPrNumberIndexRoute
  '/$owner/$repo/pull/$pull_number': typeof OwnerRepoPullPull_numberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/test': typeof TestRoute
  '/pr/$prNumber': typeof PrPrNumberRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/test': typeof AuthTestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pr/$prNumber/diff': typeof PrPrNumberDiffRoute
  '/pr/$prNumber/': typeof PrPrNumberIndexRoute
  '/$owner/$repo/pull/$pull_number': typeof OwnerRepoPullPull_numberRouteRouteWithChildren
  '/$owner/$repo/pull/$pull_number/': typeof OwnerRepoPullPull_numberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/test'
    | '/pr/$prNumber'
    | '/auth/login'
    | '/auth/test'
    | '/api/auth/$'
    | '/pr/$prNumber/diff'
    | '/pr/$prNumber/'
    | '/$owner/$repo/pull/$pull_number'
    | '/$owner/$repo/pull/$pull_number/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/test'
    | '/auth/login'
    | '/auth/test'
    | '/api/auth/$'
    | '/pr/$prNumber/diff'
    | '/pr/$prNumber'
    | '/$owner/$repo/pull/$pull_number'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/test'
    | '/pr/$prNumber'
    | '/auth/login'
    | '/auth/test'
    | '/api/auth/$'
    | '/pr/$prNumber/diff'
    | '/pr/$prNumber/'
    | '/$owner/$repo/pull/$pull_number'
    | '/$owner/$repo/pull/$pull_number/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  TestRoute: typeof TestRoute
  PrPrNumberRouteRoute: typeof PrPrNumberRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthTestRoute: typeof AuthTestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  OwnerRepoPullPull_numberRouteRoute: typeof OwnerRepoPullPull_numberRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/test': {
      id: '/auth/test'
      path: '/auth/test'
      fullPath: '/auth/test'
      preLoaderRoute: typeof AuthTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pr/$prNumber': {
      id: '/pr/$prNumber'
      path: '/pr/$prNumber'
      fullPath: '/pr/$prNumber'
      preLoaderRoute: typeof PrPrNumberRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pr/$prNumber/': {
      id: '/pr/$prNumber/'
      path: '/'
      fullPath: '/pr/$prNumber/'
      preLoaderRoute: typeof PrPrNumberIndexRouteImport
      parentRoute: typeof PrPrNumberRouteRoute
    }
    '/pr/$prNumber/diff': {
      id: '/pr/$prNumber/diff'
      path: '/diff'
      fullPath: '/pr/$prNumber/diff'
      preLoaderRoute: typeof PrPrNumberDiffRouteImport
      parentRoute: typeof PrPrNumberRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/pull/$pull_number': {
      id: '/$owner/$repo/pull/$pull_number'
      path: '/$owner/$repo/pull/$pull_number'
      fullPath: '/$owner/$repo/pull/$pull_number'
      preLoaderRoute: typeof OwnerRepoPullPull_numberRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/pull/$pull_number/': {
      id: '/$owner/$repo/pull/$pull_number/'
      path: '/'
      fullPath: '/$owner/$repo/pull/$pull_number/'
      preLoaderRoute: typeof OwnerRepoPullPull_numberIndexRouteImport
      parentRoute: typeof OwnerRepoPullPull_numberRouteRoute
    }
  }
}

interface PrPrNumberRouteRouteChildren {
  PrPrNumberDiffRoute: typeof PrPrNumberDiffRoute
  PrPrNumberIndexRoute: typeof PrPrNumberIndexRoute
}

const PrPrNumberRouteRouteChildren: PrPrNumberRouteRouteChildren = {
  PrPrNumberDiffRoute: PrPrNumberDiffRoute,
  PrPrNumberIndexRoute: PrPrNumberIndexRoute,
}

const PrPrNumberRouteRouteWithChildren = PrPrNumberRouteRoute._addFileChildren(
  PrPrNumberRouteRouteChildren,
)

interface OwnerRepoPullPull_numberRouteRouteChildren {
  OwnerRepoPullPull_numberIndexRoute: typeof OwnerRepoPullPull_numberIndexRoute
}

const OwnerRepoPullPull_numberRouteRouteChildren: OwnerRepoPullPull_numberRouteRouteChildren =
  {
    OwnerRepoPullPull_numberIndexRoute: OwnerRepoPullPull_numberIndexRoute,
  }

const OwnerRepoPullPull_numberRouteRouteWithChildren =
  OwnerRepoPullPull_numberRouteRoute._addFileChildren(
    OwnerRepoPullPull_numberRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  TestRoute: TestRoute,
  PrPrNumberRouteRoute: PrPrNumberRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthTestRoute: AuthTestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  OwnerRepoPullPull_numberRouteRoute:
    OwnerRepoPullPull_numberRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
