/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTestRouteImport } from './routes/auth/test'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedTestRouteImport } from './routes/_authenticated/test'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedPrPrNumberRouteRouteImport } from './routes/_authenticated/pr.$prNumber/route'
import { Route as AuthenticatedPrPrNumberIndexRouteImport } from './routes/_authenticated/pr.$prNumber/index'
import { Route as AuthenticatedPrPrNumberDiffRouteImport } from './routes/_authenticated/pr.$prNumber/diff'
import { Route as AuthenticatedOwnerRepoPullPull_numberRouteRouteImport } from './routes/_authenticated/$owner.$repo.pull.$pull_number/route'
import { Route as AuthenticatedOwnerRepoPullPull_numberIndexRouteImport } from './routes/_authenticated/$owner.$repo.pull.$pull_number/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTestRoute = AuthTestRouteImport.update({
  id: '/auth/test',
  path: '/auth/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTestRoute = AuthenticatedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPrPrNumberRouteRoute =
  AuthenticatedPrPrNumberRouteRouteImport.update({
    id: '/pr/$prNumber',
    path: '/pr/$prNumber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrPrNumberIndexRoute =
  AuthenticatedPrPrNumberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPrPrNumberRouteRoute,
  } as any)
const AuthenticatedPrPrNumberDiffRoute =
  AuthenticatedPrPrNumberDiffRouteImport.update({
    id: '/diff',
    path: '/diff',
    getParentRoute: () => AuthenticatedPrPrNumberRouteRoute,
  } as any)
const AuthenticatedOwnerRepoPullPull_numberRouteRoute =
  AuthenticatedOwnerRepoPullPull_numberRouteRouteImport.update({
    id: '/$owner/$repo/pull/$pull_number',
    path: '/$owner/$repo/pull/$pull_number',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerRepoPullPull_numberIndexRoute =
  AuthenticatedOwnerRepoPullPull_numberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOwnerRepoPullPull_numberRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof AuthenticatedTestRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/test': typeof AuthTestRoute
  '/pr/$prNumber': typeof AuthenticatedPrPrNumberRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pr/$prNumber/diff': typeof AuthenticatedPrPrNumberDiffRoute
  '/pr/$prNumber/': typeof AuthenticatedPrPrNumberIndexRoute
  '/$owner/$repo/pull/$pull_number': typeof AuthenticatedOwnerRepoPullPull_numberRouteRouteWithChildren
  '/$owner/$repo/pull/$pull_number/': typeof AuthenticatedOwnerRepoPullPull_numberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof AuthenticatedTestRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/test': typeof AuthTestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pr/$prNumber/diff': typeof AuthenticatedPrPrNumberDiffRoute
  '/pr/$prNumber': typeof AuthenticatedPrPrNumberIndexRoute
  '/$owner/$repo/pull/$pull_number': typeof AuthenticatedOwnerRepoPullPull_numberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/test': typeof AuthenticatedTestRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/test': typeof AuthTestRoute
  '/_authenticated/pr/$prNumber': typeof AuthenticatedPrPrNumberRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/pr/$prNumber/diff': typeof AuthenticatedPrPrNumberDiffRoute
  '/_authenticated/pr/$prNumber/': typeof AuthenticatedPrPrNumberIndexRoute
  '/_authenticated/$owner/$repo/pull/$pull_number': typeof AuthenticatedOwnerRepoPullPull_numberRouteRouteWithChildren
  '/_authenticated/$owner/$repo/pull/$pull_number/': typeof AuthenticatedOwnerRepoPullPull_numberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/auth/login'
    | '/auth/test'
    | '/pr/$prNumber'
    | '/api/auth/$'
    | '/pr/$prNumber/diff'
    | '/pr/$prNumber/'
    | '/$owner/$repo/pull/$pull_number'
    | '/$owner/$repo/pull/$pull_number/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/auth/login'
    | '/auth/test'
    | '/api/auth/$'
    | '/pr/$prNumber/diff'
    | '/pr/$prNumber'
    | '/$owner/$repo/pull/$pull_number'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/test'
    | '/auth/login'
    | '/auth/test'
    | '/_authenticated/pr/$prNumber'
    | '/api/auth/$'
    | '/_authenticated/pr/$prNumber/diff'
    | '/_authenticated/pr/$prNumber/'
    | '/_authenticated/$owner/$repo/pull/$pull_number'
    | '/_authenticated/$owner/$repo/pull/$pull_number/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthTestRoute: typeof AuthTestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/test': {
      id: '/auth/test'
      path: '/auth/test'
      fullPath: '/auth/test'
      preLoaderRoute: typeof AuthTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/test': {
      id: '/_authenticated/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthenticatedTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pr/$prNumber': {
      id: '/_authenticated/pr/$prNumber'
      path: '/pr/$prNumber'
      fullPath: '/pr/$prNumber'
      preLoaderRoute: typeof AuthenticatedPrPrNumberRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pr/$prNumber/': {
      id: '/_authenticated/pr/$prNumber/'
      path: '/'
      fullPath: '/pr/$prNumber/'
      preLoaderRoute: typeof AuthenticatedPrPrNumberIndexRouteImport
      parentRoute: typeof AuthenticatedPrPrNumberRouteRoute
    }
    '/_authenticated/pr/$prNumber/diff': {
      id: '/_authenticated/pr/$prNumber/diff'
      path: '/diff'
      fullPath: '/pr/$prNumber/diff'
      preLoaderRoute: typeof AuthenticatedPrPrNumberDiffRouteImport
      parentRoute: typeof AuthenticatedPrPrNumberRouteRoute
    }
    '/_authenticated/$owner/$repo/pull/$pull_number': {
      id: '/_authenticated/$owner/$repo/pull/$pull_number'
      path: '/$owner/$repo/pull/$pull_number'
      fullPath: '/$owner/$repo/pull/$pull_number'
      preLoaderRoute: typeof AuthenticatedOwnerRepoPullPull_numberRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$owner/$repo/pull/$pull_number/': {
      id: '/_authenticated/$owner/$repo/pull/$pull_number/'
      path: '/'
      fullPath: '/$owner/$repo/pull/$pull_number/'
      preLoaderRoute: typeof AuthenticatedOwnerRepoPullPull_numberIndexRouteImport
      parentRoute: typeof AuthenticatedOwnerRepoPullPull_numberRouteRoute
    }
  }
}

interface AuthenticatedPrPrNumberRouteRouteChildren {
  AuthenticatedPrPrNumberDiffRoute: typeof AuthenticatedPrPrNumberDiffRoute
  AuthenticatedPrPrNumberIndexRoute: typeof AuthenticatedPrPrNumberIndexRoute
}

const AuthenticatedPrPrNumberRouteRouteChildren: AuthenticatedPrPrNumberRouteRouteChildren =
  {
    AuthenticatedPrPrNumberDiffRoute: AuthenticatedPrPrNumberDiffRoute,
    AuthenticatedPrPrNumberIndexRoute: AuthenticatedPrPrNumberIndexRoute,
  }

const AuthenticatedPrPrNumberRouteRouteWithChildren =
  AuthenticatedPrPrNumberRouteRoute._addFileChildren(
    AuthenticatedPrPrNumberRouteRouteChildren,
  )

interface AuthenticatedOwnerRepoPullPull_numberRouteRouteChildren {
  AuthenticatedOwnerRepoPullPull_numberIndexRoute: typeof AuthenticatedOwnerRepoPullPull_numberIndexRoute
}

const AuthenticatedOwnerRepoPullPull_numberRouteRouteChildren: AuthenticatedOwnerRepoPullPull_numberRouteRouteChildren =
  {
    AuthenticatedOwnerRepoPullPull_numberIndexRoute:
      AuthenticatedOwnerRepoPullPull_numberIndexRoute,
  }

const AuthenticatedOwnerRepoPullPull_numberRouteRouteWithChildren =
  AuthenticatedOwnerRepoPullPull_numberRouteRoute._addFileChildren(
    AuthenticatedOwnerRepoPullPull_numberRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTestRoute: typeof AuthenticatedTestRoute
  AuthenticatedPrPrNumberRouteRoute: typeof AuthenticatedPrPrNumberRouteRouteWithChildren
  AuthenticatedOwnerRepoPullPull_numberRouteRoute: typeof AuthenticatedOwnerRepoPullPull_numberRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTestRoute: AuthenticatedTestRoute,
  AuthenticatedPrPrNumberRouteRoute:
    AuthenticatedPrPrNumberRouteRouteWithChildren,
  AuthenticatedOwnerRepoPullPull_numberRouteRoute:
    AuthenticatedOwnerRepoPullPull_numberRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthTestRoute: AuthTestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
